title: "Josh's Collection of Absolute Trash (Josh's CAT)"
tagline: "Pell-mell tales in nerd esoteria"
url: https://joshuamegnauth54.github.io
production_url: https://joshuamegnauth54.github.io
locale: en_US
markdown: kramdown

social:
  name: Joshua Megnauth

author:
  name: Joshua Megnauth
  github: joshuamegnauth54

# https://github.com/dracula/gh-pages
remote_theme: "dracula/gh-pages"

defaults:
  values:
    show_date: true
