title = "Josh Megnauth's programming ramblings"
description = "Rust and Linux"
base_url = "https://joshuamegnauth54.github.io"

compile_sass = true
build_search_index = false
generate_feeds = true
theme = "tanuki"
taxonomies = [
    { name = "tags", feed = true },
    { name = "authors", feed = true }
]

[markdown]
highlight_code = true
highlight_theme = "catppuccin-mocha"
render_emoji = true
smart_punctuation = true

[extra]
mode = "blog"

[extra.social]
codeberg = "https://codeberg.org/jo_sh"
gitlab = "https://gitlab.com/joshuamegnauth54"
github = "https://github.com/joshuamegnauth54"
redox = "https://gitlab.redox-os.org/josh"

[[extra.nav]]
name = "About"
url = "/about/"

[[extra.nav]]
name = "Blog"
url = "/blog/"
